Update Checkstyle.yml

diff --git a/Checkstyle.yml b/Checkstyle.yml
--- a/Checkstyle.yml
+++ b/Checkstyle.yml
@@ -1,6 +1,6 @@
 # This is a basic workflow to help you get started with Actions
 
-name: CI
+name: checkstyle
 
 # Controls when the workflow will run
 on:
@@ -13,24 +13,36 @@ on:
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
+# The checkstyle job
 jobs:
-  # This workflow contains a single job called "build"
   build:
+    name: Checkstyle
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
-
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v3
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
-
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      # Set up the environment
+      - name: Env setup
+        run: | 
+          mkdir -p /opt/lib
+          wget -q -O /opt/lib/checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.6/checkstyle-10.12.6-all.jar
+          cd "${GITHUB_WORKSPACE}"
+          
+      # Configures and runs checkstyle
+      - name: Run Checkstyle
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          exec java -jar /opt/lib/checkstyle.jar "." -c "checkstyle_checks.xml" -f xml > results.xml
+
+      - name: Print Results
+        run: echo "$(cat results.xml)"
+
+      - name: Check Results
+        run:  |
+          if grep -q error results.xml; then
+            echo "Checkstyle found an error - look at the logs under Print Results for details"
+            exit 1
+          else
+            echo "No errors found!"
+          fi
